package net.rkr1410.yaklox.tools

import java.io.File

internal class AstClassGen(private val outputDir: String, private val baseName: String) {
    fun generateAst(serializedTypes: List<String>) {
        val typedefs = serializedTypes.map(TypeDef::of)
        val baseClassDefinition= """
                |// autogenerated
                |package net.rkr1410.yaklox
                
                |internal abstract class $baseName {
                |
                |    abstract fun <R> accept(visitor: Visitor<R>): R
                |    interface Visitor<R> {
                         |${each(tab2() to "\n", typedefs.map(::visitorMethod))}
                |    }
                |    
                     |${each("" to "\n", typedefs.map(::astType))}
                |}
            """.trimMargin()

        File("$outputDir/$baseName.kt").printWriter().use { it.println(baseClassDefinition) }
    }

    private fun tab2() = "    ".repeat(2)
    private fun each(preAndPostfix: Pair<String?, String>, items: List<String>) =
        items.joinToString(preAndPostfix.second) { "${preAndPostfix.first?:""}$it" }.trimEnd()

    private fun visitorMethod(td: TypeDef) = "fun visit${td.className}$baseName(expression: ${td.className}): R"
    private fun astType(td: TypeDef) =
        """
            |    class ${td.className}(
                    |${each("${tab2()}val " to ",\n", td.properties)}
            |    ): Expression() {
            |       override fun <R> accept(visitor: Visitor<R>) = visitor.visit${td.className}$baseName(this)
            |    }
            |
        """.trimMargin()
}

class TypeDef(val className: String, val properties: List<String>) {
    companion object {
        fun of(serialized: String): TypeDef {
            val className = serialized.split("=")[0].trim()
            val properties = serialized.split("=")[1].split(", ").map(String::trim).toList()
            return TypeDef(className, properties)
        }
    }
}

fun main() {
    val dir = "app/src/main/kotlin/net/rkr1410/yaklox/"
    //val dir = "/Users/pafau/tmp/"
    AstClassGen(dir, "Expression").generateAst(listOf(
        "Binary   = left: Expression, operator: Token, right: Expression",
        "Grouping = expr: Expression",
        "Literal  = value: Any?",
        "Unary    = operator: Token, right: Expression",
    ))

}